import { NitroConfig } from '../../config/NitroConfig.js'
import { isCppFile, isNotDuplicate } from '../../syntax/helpers.js'
import type { SourceFile } from '../../syntax/SourceFile.js'
import { indent, toLowerCamelCase } from '../../utils.js'

export interface MSBuildFile extends Omit<SourceFile, 'language'> {
  language: 'xml'
}

/**
 * The preprocessor define set by the generated `.props`, asserted by the
 * generated `<Name>Autolinking.cpp` so a mis-configured `.vcxproj` fails loudly.
 */
export function getBuildingWithGeneratedMSBuildDefinition(): string {
  const name = NitroConfig.current.getWindowsProjectName()
  const upper = toLowerCamelCase(name).toUpperCase()
  return `BUILDING_${upper}_WITH_GENERATED_MSBUILD`
}

function msbuildBanner(filename: string): string {
  return `  ${filename}
  This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
  https://github.com/mrousavy/nitro
  Copyright © Marc Rousavy @ Margelo`
}

/** `[a, b], c.cpp` -> `prefix\a\b\c.cpp` for an MSBuild `Include`. */
function toMSBuildInclude(prefix: string, file: SourceFile): string {
  return [prefix, ...file.subdirectory, file.name].join('\\')
}

/**
 * Generates `<Name>+autolinking.props` and `<Name>+autolinking.targets` for Windows.
 *
 * A consuming Nitro module's `.vcxproj` imports the `.props` after
 * `Microsoft.Cpp.props` and the `.targets` after `Microsoft.Cpp.targets`. Between
 * them they:
 *  - import `react-native-nitro-modules`' `ConsumeNitroModules.{props,targets}`
 *    (`NITRO_USING_SHARED_LIBRARY`, include paths, the `NitroModules.lib` reference,
 *    the `<NitroModules/*.hpp>` shim generation),
 *  - add every Nitrogen-generated shared C++ spec + the autolinking entry point as
 *    `<ClCompile>` items,
 *  - add the generated include directories.
 */
export function createMSBuildExtension(files: SourceFile[]): MSBuildFile[] {
  const name = NitroConfig.current.getWindowsProjectName()
  const autolinkingClassName = `${name}Autolinking`
  const buildingWithDefinition = getBuildingWithGeneratedMSBuildDefinition()

  const nitroModulesDirProp = `<NitroModulesDir Condition="'$(NitroModulesDir)' == ''">$([MSBuild]::GetDirectoryNameOfFileAbove($(SolutionDir), 'node_modules\\react-native-nitro-modules\\package.json'))\\node_modules\\react-native-nitro-modules\\</NitroModulesDir>`

  const sharedCppFiles = files
    .filter((f) => f.platform === 'shared' && isCppFile(f))
    .map((f) => toMSBuildInclude('$(NitrogenDir)..\\shared\\c++', f))
    .filter(isNotDuplicate)

  const propsCode = `<?xml version="1.0" encoding="utf-8"?>
<!--
${msbuildBanner(`${name}+autolinking.props`)}

  Import this from your Nitro module's .vcxproj, after Microsoft.Cpp.props:
    <Import Project="..\\..\\nitrogen\\generated\\windows\\${name}+autolinking.props" />
  and ${name}+autolinking.targets after Microsoft.Cpp.targets.
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Nitrogen">
    <NitrogenDir>$(MSBuildThisFileDirectory)</NitrogenDir>
    ${nitroModulesDirProp}
  </PropertyGroup>

  <Import Project="$(NitroModulesDir)windows\\ConsumeNitroModules.props" />

  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>${buildingWithDefinition};%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(NitrogenDir)..\\shared\\c++;$(NitrogenDir);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>

  <ItemGroup Label="Nitrogen generated (shared C++)">
${indent(sharedCppFiles.map((p) => `<ClCompile Include="${p}" />`).join('\n'), '    ')}
    <ClCompile Include="$(NitrogenDir)${autolinkingClassName}.cpp" />
    <ClInclude Include="$(NitrogenDir)${autolinkingClassName}.hpp" />
  </ItemGroup>
</Project>`

  const targetsCode = `<?xml version="1.0" encoding="utf-8"?>
<!--
${msbuildBanner(`${name}+autolinking.targets`)}

  Import this from your Nitro module's .vcxproj, after Microsoft.Cpp.targets.
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Nitrogen">
    ${nitroModulesDirProp}
  </PropertyGroup>

  <Import Project="$(NitroModulesDir)windows\\ConsumeNitroModules.targets" />
</Project>`

  return [
    {
      content: propsCode,
      name: `${name}+autolinking.props`,
      language: 'xml',
      platform: 'windows',
      subdirectory: [],
    },
    {
      content: targetsCode,
      name: `${name}+autolinking.targets`,
      language: 'xml',
      platform: 'windows',
      subdirectory: [],
    },
  ]
}
