import { NitroConfig } from '../../config/NitroConfig.js'
import { createCppHybridObjectRegistration } from '../../syntax/c++/CppHybridObjectRegistration.js'
import { includeHeader } from '../../syntax/c++/includeNitroHeader.js'
import { createFileMetadataString, isNotDuplicate } from '../../syntax/helpers.js'
import type { SourceFile, SourceImport } from '../../syntax/SourceFile.js'
import { indent } from '../../utils.js'
import { getBuildingWithGeneratedMSBuildDefinition } from './createMSBuildExtension.js'

/**
 * Generates `<Name>Autolinking.hpp` / `.cpp` for Windows - a single
 * `registerHybridObjects()` entry point that registers every autolinked C++
 * HybridObject into Nitro's shared `HybridObjectRegistry` (which lives in
 * `NitroModules.dll`).
 *
 * The consuming Nitro module calls it from its own `IReactPackageProvider`.
 */
export function createHybridObjectInitializer(): SourceFile[] {
  const cxxNamespace = NitroConfig.current.getCxxNamespace('c++')
  const projectName = NitroConfig.current.getWindowsProjectName()
  const autolinkingClassName = `${projectName}Autolinking`
  const buildingWithDefinition = getBuildingWithGeneratedMSBuildDefinition()

  const autolinkedHybridObjects = NitroConfig.current.getAutolinkedHybridObjects()

  const cppImports: SourceImport[] = []
  const cppRegistrations: string[] = []
  for (const hybridObjectName of Object.keys(autolinkedHybridObjects)) {
    const implementation = NitroConfig.current.getPlatformAutolinkedImplementation(
      hybridObjectName,
      'windows'
    )
    if (implementation == null) {
      // This HybridObject is not autolinked on Windows.
      continue
    }
    if (implementation.language !== 'c++') {
      throw new Error(
        `The HybridObject "${hybridObjectName}" cannot be autolinked on Windows - ` +
          `language "${implementation.language}" is not supported on Windows! Only "c++" is.`
      )
    }

    const { cppCode, requiredImports } = createCppHybridObjectRegistration({
      hybridObjectName: hybridObjectName,
      cppClassName: implementation.implementationClassName,
    })
    cppImports.push(...requiredImports)
    cppRegistrations.push(cppCode)
  }

  const includes = cppImports
    .map((i) => includeHeader(i))
    .filter(isNotDuplicate)
    .join('\n')

  const hppCode = `
${createFileMetadataString(`${autolinkingClassName}.hpp`)}

#pragma once

namespace ${cxxNamespace} {

/**
 * Registers every C++ HybridObject of "${projectName}" in Nitro's shared
 * \`HybridObjectRegistry\` (which lives in \`NitroModules.dll\`).
 *
 * Call this from your React Native Windows package provider, before
 * \`NitroModules.install()\` runs:
 * \`\`\`cpp
 * void ReactPackageProvider::CreatePackage(IReactPackageBuilder const& packageBuilder) noexcept {
 *   ${cxxNamespace}::registerHybridObjects();
 *   AddAttributedModules(packageBuilder, true);
 * }
 * \`\`\`
 *
 * This method is idempotent - calling it more than once has no additional effect.
 */
void registerHybridObjects();

} // namespace ${cxxNamespace}
  `.trim()

  const cppCode = `
${createFileMetadataString(`${autolinkingClassName}.cpp`)}

#ifndef ${buildingWithDefinition}
#error ${autolinkingClassName}.cpp is not being built with the autogenerated ${projectName}+autolinking.props. Is a different .vcxproj building this?
#endif

#include "${autolinkingClassName}.hpp"

#include <mutex>

#include <NitroModules/HybridObjectRegistry.hpp>

${includes}

namespace ${cxxNamespace} {

void registerHybridObjects() {
  using namespace margelo::nitro;

  static std::once_flag onceFlag;
  std::call_once(onceFlag, []() {
    ${indent(cppRegistrations.join('\n'), '    ')}
  });
}

} // namespace ${cxxNamespace}
  `.trim()

  return [
    {
      content: hppCode,
      name: `${autolinkingClassName}.hpp`,
      language: 'c++',
      platform: 'windows',
      subdirectory: [],
    },
    {
      content: cppCode,
      name: `${autolinkingClassName}.cpp`,
      language: 'c++',
      platform: 'windows',
      subdirectory: [],
    },
  ]
}
